/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import assert from 'node:assert/strict'
import { after, afterEach, describe, test } from 'node:test'

import { Window } from 'happy-dom'

import type { UserProfile } from '../../types'

const domWindow = new Window()
const domGlobals = [
  'window',
  'document',
  'navigator',
  'HTMLElement',
  'HTMLButtonElement',
  'HTMLDivElement',
  'HTMLInputElement',
  'HTMLTextAreaElement',
  'HTMLLabelElement',
  'HTMLSpanElement',
  'SVGElement',
  'Node',
  'Element',
  'Event',
  'CustomEvent',
  'MutationObserver',
  'requestAnimationFrame',
  'cancelAnimationFrame',
  'getComputedStyle',
] as const

for (const key of domGlobals) {
  Object.defineProperty(globalThis, key, {
    configurable: true,
    value: domWindow[key],
  })
}

Object.defineProperty(globalThis, 'localStorage', {
  configurable: true,
  value: domWindow.localStorage,
})

Object.defineProperty(globalThis, 'ResizeObserver', {
  configurable: true,
  value: class ResizeObserver {
    observe() {}
    unobserve() {}
    disconnect() {}
  },
})

Object.defineProperty(domWindow, 'matchMedia', {
  configurable: true,
  value: () => ({
    matches: false,
    media: '',
    onchange: null,
    addListener() {},
    removeListener() {},
    addEventListener() {},
    removeEventListener() {},
    dispatchEvent() {
      return false
    },
  }),
})
Object.defineProperty(globalThis, 'matchMedia', {
  configurable: true,
  value: domWindow.matchMedia,
})

const { cleanup, fireEvent, render, waitFor } =
  await import('@testing-library/react')
const { createInstance } = await import('i18next')
const { I18nextProvider, initReactI18next } = await import('react-i18next')
const { Toaster } = await import('sonner')
const { api } = await import('@/lib/api')
const { useAuthStore } = await import('@/stores/auth-store')
const { VisionInterceptionCard } = await import('../vision-interception-card')
const { DEFAULT_VISION_PROMPT } = await import('../../lib/vision')

const originalPut = api.put
const i18n = createInstance()
await i18n.use(initReactI18next).init({
  lng: 'en',
  resources: {
    en: {
      translation: {
        'Vision Interception': 'Vision Interception',
        'Replace images with text descriptions when the model matches the configured suffix.':
          'Replace images with text descriptions when the model matches the configured suffix.',
        'Enable Vision Interception': 'Enable Vision Interception',
        'Images in matching requests are replaced with descriptions generated by the configured vision model.':
          'Images in matching requests are replaced with descriptions generated by the configured vision model.',
        'Vision Model': 'Vision Model',
        'Vision model name': 'Vision model name',
        'Model Suffix': 'Model Suffix',
        'e.g. -vision': 'e.g. -vision',
        'Prompt Template': 'Prompt Template',
        'pHash Threshold': 'pHash Threshold',
        'Hamming distance for near-duplicate image clustering. 0 disables perceptual deduplication.':
          'Hamming distance for near-duplicate image clustering. 0 disables perceptual deduplication.',
        Save: 'Save',
        'Vision settings saved': 'Vision settings saved',
        'Failed to update settings': 'Failed to update settings',
      },
    },
  },
})

const profileBase: UserProfile = {
  id: 7,
  username: 'vision-user',
  display_name: 'Vision User',
  role: 1,
  group: 'default',
  quota: 100,
  used_quota: 0,
  request_count: 0,
  status: 1,
  aff_count: 0,
  aff_quota: 0,
  aff_history_quota: 0,
  created_time: 1,
}

function renderVisionCard(profile: UserProfile, onProfileUpdate = () => {}) {
  return render(
    <I18nextProvider i18n={i18n}>
      <VisionInterceptionCard
        profile={profile}
        onProfileUpdate={onProfileUpdate}
      />
      <Toaster />
    </I18nextProvider>
  )
}

describe('Vision interception profile card', () => {
  afterEach(() => {
    cleanup()
    api.put = originalPut
    useAuthStore.getState().auth.setUser(null)
  })
  after(() => domWindow.close())

  test('shows the canonical default prompt when no prompt is saved', () => {
    const rendered = renderVisionCard({
      ...profileBase,
      setting: JSON.stringify({ vision: { enabled: false } }),
    })

    const prompt = rendered.getByRole('textbox', {
      name: 'Prompt Template',
    }) as HTMLTextAreaElement
    assert.equal(prompt.value, DEFAULT_VISION_PROMPT)
  })

  test('normalizes a blank prompt, submits the threshold, updates auth state, and refreshes the profile', async () => {
    const requests: unknown[] = []
    let completeRequest!: () => void
    api.put = (async (_url: string, data: unknown) => {
      requests.push(data)
      await new Promise<void>((resolve) => {
        completeRequest = resolve
      })
      return { data: { success: true } }
    }) as typeof api.put
    useAuthStore.getState().auth.setUser({
      id: 7,
      username: 'vision-user',
      role: 1,
      setting: JSON.stringify({ language: 'ja' }),
    })
    let refreshCount = 0
    const rendered = renderVisionCard(
      {
        ...profileBase,
        setting: JSON.stringify({
          vision: {
            enabled: true,
            vision_model: 'vision-model',
            vision_suffix: '-vision',
            prompt_template: 'Existing prompt',
            phash_threshold: 4,
          },
        }),
      },
      () => {
        refreshCount++
      }
    )

    fireEvent.change(
      rendered.getByRole('textbox', { name: 'Prompt Template' }),
      { target: { value: '   ' } }
    )
    fireEvent.change(
      rendered.getByRole('spinbutton', { name: 'pHash Threshold' }),
      { target: { value: '64' } }
    )
    const saveButton = rendered.getByRole('button', {
      name: 'Save',
    }) as HTMLButtonElement
    fireEvent.click(saveButton)

    await waitFor(() => assert.equal(requests.length, 1))
    assert.equal(saveButton.disabled, true)
    assert.equal(saveButton.closest('form')?.getAttribute('aria-busy'), 'true')
    assert.deepEqual(requests[0], {
      vision: {
        enabled: true,
        vision_model: 'vision-model',
        vision_suffix: '-vision',
        prompt_template: DEFAULT_VISION_PROMPT,
        phash_threshold: 64,
      },
    })
    completeRequest()
    await waitFor(() => assert.equal(refreshCount, 1))
    assert.equal(saveButton.disabled, false)
    assert.equal(saveButton.closest('form')?.getAttribute('aria-busy'), 'false')

    const authSetting = useAuthStore.getState().auth.user?.setting
    assert.equal(typeof authSetting, 'string')
    const parsedSetting = JSON.parse(authSetting as string)
    assert.equal(parsedSetting.language, 'ja')
    assert.deepEqual(parsedSetting.vision, {
      enabled: true,
      vision_model: 'vision-model',
      vision_suffix: '-vision',
      prompt_template: DEFAULT_VISION_PROMPT,
      phash_threshold: 64,
    })
    assert.equal(
      (
        rendered.getByRole('textbox', {
          name: 'Prompt Template',
        }) as HTMLTextAreaElement
      ).value,
      DEFAULT_VISION_PROMPT
    )
  })

  test('does not submit an out-of-range threshold', async () => {
    const requests: unknown[] = []
    api.put = (async (_url: string, data: unknown) => {
      requests.push(data)
      return { data: { success: true } }
    }) as typeof api.put
    const rendered = renderVisionCard({
      ...profileBase,
      setting: JSON.stringify({ vision: { enabled: false } }),
    })
    const threshold = rendered.getByRole('spinbutton', {
      name: 'pHash Threshold',
    }) as HTMLInputElement
    const descriptionId = threshold.getAttribute('aria-describedby')
    assert.ok(descriptionId)
    assert.match(
      rendered.container.querySelector(`[id="${descriptionId}"]`)
        ?.textContent ?? '',
      /0 disables/
    )

    fireEvent.change(threshold, { target: { value: '65' } })
    assert.equal(threshold.validity.rangeOverflow, true)
    fireEvent.click(rendered.getByRole('button', { name: 'Save' }))
    await Promise.resolve()

    assert.equal(requests.length, 0)
  })

  test('keeps auth and profile state unchanged when the API rejects the save', async () => {
    api.put = (async () => ({
      data: { success: false, message: 'provider rejected settings' },
    })) as typeof api.put
    const originalUser = {
      id: 7,
      username: 'vision-user',
      role: 1,
      setting: JSON.stringify({ language: 'ja' }),
    }
    useAuthStore.getState().auth.setUser(originalUser)
    let refreshCount = 0
    const rendered = renderVisionCard(
      {
        ...profileBase,
        setting: JSON.stringify({
          vision: {
            enabled: true,
            vision_model: 'vision-model',
            vision_suffix: '-vision',
            prompt_template: 'Existing prompt',
            phash_threshold: 4,
          },
        }),
      },
      () => {
        refreshCount++
      }
    )

    fireEvent.change(
      rendered.getByRole('spinbutton', { name: 'pHash Threshold' }),
      { target: { value: '12' } }
    )
    fireEvent.click(rendered.getByRole('button', { name: 'Save' }))

    await waitFor(() =>
      assert.match(document.body.textContent ?? '', /Failed to update settings/)
    )
    assert.equal(refreshCount, 0)
    assert.deepEqual(useAuthStore.getState().auth.user, originalUser)
    assert.equal(
      (rendered.getByRole('button', { name: 'Save' }) as HTMLButtonElement)
        .disabled,
      false
    )
  })
})
